version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - go_hackernews_clone:/var/lib/postgresql/data/


volumes:
  go_hackernews_clone:
